export const patientBundle = {
    "resourceType":"Bundle",
    "id":"19118be1-cddf-4cbc-aefb-0ccbf2abdca3",
    "meta":{
        "lastUpdated":"2015-12-11T13:28:44.474-05:00"
    },
    "type":"searchset",
    "total":5967,
    "link":[
        {
            "relation":"self",
            "url":"http://fhirtest.uhn.ca/baseDstu2/Patient"
        },
        {
            "relation":"next",
            "url":"http://fhirtest.uhn.ca/baseDstu2?_getpages=a43ae02a-7bb3-493d-b567-4cb672c30558&_getpagesoffset=10&_count=10&_pretty=true&_bundletype=searchset"
        }
    ],
    "entry":[
        {
            "fullUrl":"http://fhirtest.uhn.ca/baseDstu2/Patient/1",
            "resource":{
                "resourceType":"Patient",
                "id":"1",
                "meta":{
                    "versionId":"14",
                    "lastUpdated":"2015-11-30T13:23:07.529-05:00"
                },
                "text":{
                    "status":"generated",
                    "div":"<div><table class=\"hapiPropertyTable\"><tbody><tr><td>Date of birth</td><td><span>31 December 1974</span></td></tr></tbody></table></div>"
                },
                "active":false,
                "gender":"male",
                "birthDate":"1975-01-01T00:00:00.000Z",
                "deceasedBoolean":false,
                "multipleBirthBoolean":false
            },
            "search":{
                "mode":"match"
            }
        },
        {
            "fullUrl":"http://fhirtest.uhn.ca/baseDstu2/Patient/843791",
            "resource":{
                "resourceType":"Patient",
                "id":"843791",
                "meta":{
                    "versionId":"14",
                    "lastUpdated":"2015-11-30T23:31:55.100-05:00"
                },
                "text":{
                    "status":"generated",
                    "div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"> <div class=\"hapiHeaderText\"> Peter James <b>CHALMERS </b> </div> <table class=\"hapiPropertyTable\"> <tbody> <tr> <td>Identifier</td> <td>12345</td> </tr> <tr> <td>Address</td> <td> <span>534 Erewhon St </span> <br/> <span>PleasantVille </span> <span>Vic </span> </td> </tr> <tr> <td>Date of birth</td> <td> <span>25 December 1974</span> </td> </tr> </tbody> </table> </div>"
                },
                "identifier":[
                    {
                        "use":"usual",
                        "type":{
                            "coding":[
                                {
                                    "system":"http://hl7.org/fhir/v2/0203",
                                    "code":"MR"
                                }
                            ]
                        },
                        "system":"urn:oid:1.2.36.146.595.217.0.1",
                        "value":"12345",
                        "period":{
                            "start":"2001-05-06"
                        },
                        "assigner":{
                            "display":"Acme Healthcare version new"
                        }
                    },
                    {
                        "use":"usual",
                        "type":{
                            "coding":[
                                {
                                    "system":"http://hl7.org/fhir/v2/0203",
                                    "code":"MR"
                                }
                            ]
                        },
                        "system":"urn:oid:1.2.36.146.595.217.0.2",
                        "value":"123456",
                        "period":{
                            "start":"2001-05-06"
                        },
                        "assigner":{
                            "display":"Acme Healthcare test"
                        }
                    }
                ],
                "active":true,
                "name":[
                    {
                        "use":"official",
                        "family":[
                            "ChalmersACF"
                        ],
                        "given":[
                            "Peter",
                            "James"
                        ]
                    },
                    {
                        "use":"usual",
                        "given":[
                            "Jim"
                        ]
                    }
                ],
                "telecom":[
                    {
                        "use":"home"
                    },
                    {
                        "system":"phone",
                        "value":"(03) 5555 6473",
                        "use":"work"
                    }
                ],
                "gender":"male",
                "birthDate":"1974-12-25",
                "_birthDate":{
                    "extension":[
                        {
                            "url":"http://hl7.org/fhir/StructureDefinition/patient-birthTime",
                            "valueDateTime":"1974-12-25T14:35:45-05:00"
                        }
                    ]
                },
                "deceasedBoolean":true,
                "address":[
                    {
                        "use":"home",
                        "line":[
                            "534 Erewhon St"
                        ],
                        "city":"PleasantVille",
                        "state":"Vic",
                        "postalCode":"3999"
                    }
                ],
                "contact":[
                    {
                        "relationship":[
                            {
                                "coding":[
                                    {
                                        "system":"http://hl7.org/fhir/patient-contact-relationship",
                                        "code":"partner"
                                    }
                                ]
                            }
                        ],
                        "name":{
                            "family":[
                                "du",
                                "MarchÃ   ©"
                            ],
                            "_family":[
                                {
                                    "extension":[
                                        {
                                            "url":"http://hl7.org/fhir/StructureDefinition/iso21090-EN-qualifier",
                                            "valueCode":"VV"
                                        }
                                    ]
                                },
                                null
                            ],
                            "given":[
                                "BÃ   ©nÃ   ©dicte"
                            ]
                        },
                        "telecom":[
                            {
                                "system":"phone",
                                "value":"+33 (237) 998327"
                            }
                        ],
                        "gender":"male",
                        "period":{
                            "start":"2012"
                        }
                    }
                ]
            },
            "search":{
                "mode":"match"
            }
        },
        {
            "fullUrl":"http://fhirtest.uhn.ca/baseDstu2/Patient/bb8a7661-fdf1-42af-9ad6-7c7c5dd99a3b",
            "resource":{
                "resourceType":"Patient",
                "id":"bb8a7661-fdf1-42af-9ad6-7c7c5dd99a3b",
                "meta":{
                    "versionId":"7",
                    "lastUpdated":"2015-11-01T23:16:42.796-05:00"
                },
                "text":{
                    "status":"generated",
                    "div":"<div><table class=\"hapiPropertyTable\"><tbody></tbody></table></div>"
                },
                "gender":"male"
            },
            "search":{
                "mode":"match"
            }
        },
        {
            "fullUrl":"http://fhirtest.uhn.ca/baseDstu2/Patient/958473",
            "resource":{
                "resourceType":"Patient",
                "id":"958473",
                "meta":{
                    "versionId":"6",
                    "lastUpdated":"2015-11-30T13:21:17.661-05:00"
                },
                "text":{
                    "status":"generated",
                    "div":"<div><table class=\"hapiPropertyTable\"><tbody></tbody></table></div>"
                },
                "active":false,
                "gender":"male",
                "deceasedBoolean":false,
                "multipleBirthBoolean":false
            },
            "search":{
                "mode":"match"
            }
        },
        {
            "fullUrl":"http://fhirtest.uhn.ca/baseDstu2/Patient/843782",
            "resource":{
                "resourceType":"Patient",
                "id":"843782",
                "meta":{
                    "versionId":"5",
                    "lastUpdated":"2015-11-02T06:48:42.258-05:00"
                },
                "text":{
                    "status":"generated",
                    "div":"<div><table class=\"hapiPropertyTable\"><tbody></tbody></table></div>"
                }
            },
            "search":{
                "mode":"match"
            }
        },
        {
            "fullUrl":"http://fhirtest.uhn.ca/baseDstu2/Patient/1548313",
            "resource":{
                "resourceType":"Patient",
                "id":"1548313",
                "meta":{
                    "versionId":"1",
                    "lastUpdated":"2015-11-12T13:07:42.156-05:00"
                },
                "extension":[
                    {
                        "url":"http://hl7.org/fhir/StructureDefinition/patient-birthTime",
                        "valueDateTime":"2001-05-06T14:35:45-05:00"
                    }
                ],
                "text":{
                    "status":"generated",
                    "div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"> \n         <div class=\"hapiHeaderText\"> \n            <b>Moody Cruzlopez</b> \n         </div> \n         <table class=\"hapiPropertyTable\"> \n            <tbody> \n               <tr> \n                  <td> Identifier</td> \n                  <td> 1548106</td> \n               </tr> \n            </tbody> \n         </table> \n      </div>"
                },
                "identifier":[
                    {
                        "use":"usual",
                        "system":"urn:oid:2.16.840.1.113883.8374.8741155",
                        "value":"47549",
                        "period":{
                            "start":"1985-02-03"
                        },
                        "assigner":{
                            "display":"WALGREEN CO"
                        }
                    }
                ],
                "active":true,
                "name":[
                    {
                        "use":"official",
                        "family":[
                            "Cruzlopez"
                        ],
                        "given":[
                            "Moody"
                        ]
                    }
                ],
                "telecom":[
                    {
                        "use":"home"
                    },
                    {
                        "system":"phone",
                        "value":"8012650890",
                        "use":"work"
                    }
                ],
                "gender":"Male",
                "birthDate":"19380731",
                "deceasedBoolean":false,
                "address":[
                    {
                        "use":"home",
                        "line":[
                            "1272 E 3997 S SUITE 215"
                        ],
                        "city":"SALT LAKE CITY",
                        "state":"UT",
                        "postalCode":"841241348"
                    }
                ],
                "contact":[
                    {
                        "relationship":[
                            {
                                "coding":[
                                    {
                                        "system":"http://hl7.org/fhir/patient-contact-relationship",
                                        "code":"partner"
                                    }
                                ]
                            }
                        ],
                        "name":{
                            "family":[
                                "du",
                                "Stice"
                            ],
                            "_family":[
                                {
                                    "extension":[
                                        {
                                            "url":"http://hl7.org/fhir/StructureDefinition/iso21090-EN-qualifier",
                                            "valueCode":"VV"
                                        }
                                    ]
                                },
                                null
                            ],
                            "given":[
                                "Kana"
                            ]
                        },
                        "telecom":[
                            {
                                "system":"phone",
                                "value":"8013501101"
                            }
                        ]
                    }
                ],
                "managingOrganization":{
                    "reference":"Organization/1547761"
                }
            },
            "search":{
                "mode":"match"
            }
        },
        {
            "fullUrl":"http://fhirtest.uhn.ca/baseDstu2/Patient/106512",
            "resource":{
                "resourceType":"Patient",
                "id":"106512",
                "meta":{
                    "versionId":"10",
                    "lastUpdated":"2015-11-02T07:12:32.956-05:00",
                    "tag":[
                        {
                            "system":"http://example.org/codes/tags",
                            "code":"record-lost",
                            "display":"Patient File Lost"
                        },
                        {
                            "system":"system52",
                            "code":"code1"
                        },
                        {
                            "system":"system1",
                            "code":"code1"
                        }
                    ]
                },
                "text":{
                    "status":"generated",
                    "div":"<div><table class=\"hapiPropertyTable\"><tbody></tbody></table></div>"
                }
            },
            "search":{
                "mode":"match"
            }
        },
        {
            "fullUrl":"http://fhirtest.uhn.ca/baseDstu2/Patient/966682",
            "resource":{
                "resourceType":"Patient",
                "id":"966682",
                "meta":{
                    "versionId":"4",
                    "lastUpdated":"2015-11-01T23:10:06.882-05:00",
                    "tag":[
                        {
                            "code":"CLOVERLEAF"
                        }
                    ]
                },
                "text":{
                    "status":"generated",
                    "div":"<div><div class=\"hapiHeaderText\"> Cloverleaf <b>ANWENDERTREFFEN </b></div><table class=\"hapiPropertyTable\"><tbody><tr><td>Identifier</td><td>345345333</td></tr><tr><td>Address</td><td><span>22 Stable Road </span><br /><span>Whitstable </span><span>Kent </span><span>CR5 1EL </span></td></tr><tr><td>Date of birth</td><td><span>24 May 1928</span></td></tr></tbody></table></div>"
                },
                "identifier":[
                    {
                        "use":"usual",
                        "type":{
                            "coding":[
                                {
                                    "system":"http://hl7.org/fhir/identifier-type",
                                    "code":"NH"
                                }
                            ]
                        },
                        "system":"urn:oid:2.16.840.1.113883.2.1.4.1",
                        "value":"345345333",
                        "assigner":{
                            "display":"NHS"
                        }
                    },
                    {
                        "use":"usual",
                        "type":{
                            "coding":[
                                {
                                    "system":"http://hl7.org/fhir/identifier-type",
                                    "code":"MR"
                                }
                            ]
                        },
                        "system":"http://www.ghh.org/identifiers",
                        "value":"4567345345",
                        "assigner":{
                            "display":"TCPAS"
                        }
                    }
                ],
                "name":[
                    {
                        "use":"official",
                        "family":[
                            "Anwendertreffen"
                        ],
                        "given":[
                            "Cloverleaf"
                        ]
                    }
                ],
                "telecom":[
                    {
                        "system":"phone",
                        "value":"277543",
                        "use":"home"
                    }
                ],
                "gender":"female",
                "birthDate":"1928-05-24",
                "address":[
                    {
                        "line":[
                            "22 Stable Road"
                        ],
                        "city":"Whitstable",
                        "state":"Kent",
                        "country":"CR5 1EL"
                    }
                ],
                "contact":[
                    {
                        "relationship":[
                            {
                                "coding":[
                                    {
                                        "system":"http://hl7.org/fhir/patient-contact-relationship",
                                        "code":"parent"
                                    }
                                ]
                            }
                        ],
                        "name":{
                            "family":[
                                "Riley"
                            ],
                            "given":[
                                "Nine"
                            ]
                        }
                    }
                ]
            },
            "search":{
                "mode":"match"
            }
        },
        {
            "fullUrl":"http://fhirtest.uhn.ca/baseDstu2/Patient/1548290",
            "resource":{
                "resourceType":"Patient",
                "id":"1548290",
                "meta":{
                    "versionId":"1",
                    "lastUpdated":"2015-11-12T13:07:41.146-05:00"
                },
                "extension":[
                    {
                        "url":"http://hl7.org/fhir/StructureDefinition/patient-birthTime",
                        "valueDateTime":"2001-05-06T14:35:45-05:00"
                    }
                ],
                "text":{
                    "status":"generated",
                    "div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"> \n         <div class=\"hapiHeaderText\"> \n            <b>Hamed Danison</b> \n         </div> \n         <table class=\"hapiPropertyTable\"> \n            <tbody> \n               <tr> \n                  <td> Identifier</td> \n                  <td> 1548267</td> \n               </tr> \n            </tbody> \n         </table> \n      </div>"
                },
                "identifier":[
                    {
                        "use":"usual",
                        "system":"urn:oid:2.16.840.1.113883.4718.9081569",
                        "value":"74067",
                        "period":{
                            "start":"1926-05-21"
                        },
                        "assigner":{
                            "display":"NEXT STEP FOOT & ANKLE CENTERS"
                        }
                    }
                ],
                "active":true,
                "name":[
                    {
                        "use":"official",
                        "family":[
                            "Danison"
                        ],
                        "given":[
                            "Hamed"
                        ]
                    }
                ],
                "telecom":[
                    {
                        "use":"home"
                    },
                    {
                        "system":"phone",
                        "value":"8014877022",
                        "use":"work"
                    }
                ],
                "gender":"Male",
                "birthDate":"19220725",
                "deceasedBoolean":false,
                "address":[
                    {
                        "use":"home",
                        "line":[
                            "835 E 248 S"
                        ],
                        "city":"SALT LAKE CITY",
                        "state":"UT",
                        "postalCode":"841022317"
                    }
                ],
                "contact":[
                    {
                        "relationship":[
                            {
                                "coding":[
                                    {
                                        "system":"http://hl7.org/fhir/patient-contact-relationship",
                                        "code":"partner"
                                    }
                                ]
                            }
                        ],
                        "name":{
                            "family":[
                                "du",
                                "Stice"
                            ],
                            "_family":[
                                {
                                    "extension":[
                                        {
                                            "url":"http://hl7.org/fhir/StructureDefinition/iso21090-EN-qualifier",
                                            "valueCode":"VV"
                                        }
                                    ]
                                },
                                null
                            ],
                            "given":[
                                "Kana"
                            ]
                        },
                        "telecom":[
                            {
                                "system":"phone",
                                "value":"8013501101"
                            }
                        ]
                    }
                ],
                "managingOrganization":{
                    "reference":"Organization/1547746"
                }
            },
            "search":{
                "mode":"match"
            }
        },
        {
            "fullUrl":"http://fhirtest.uhn.ca/baseDstu2/Patient/335890",
            "resource":{
                "resourceType":"Patient",
                "id":"335890",
                "meta":{
                    "versionId":"29",
                    "lastUpdated":"2015-12-11T00:05:16.707-05:00"
                },
                "text":{
                    "status":"generated",
                    "div":"<div>Some narrative</div>"
                },
                "active":true,
                "name":[
                    {
                        "use":"official",
                        "family":[
                            "Chalmers"
                        ],
                        "given":[
                            "Peter",
                            "James"
                        ]
                    }
                ],
                "gender":"male",
                "birthDate":"1974-12-25"
            },
            "search":{
                "mode":"match"
            }
        }
    ]
};
